### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by prem0132** [prem0132/spark-k8s-dashboard#1]
### Phase 1:

- [ ] - Sidebar positioning
- [ ] - tab to interact with the api 
- [ ] - selected api should display the json output 
- [ ] - option to add query after the primary api
- [ ] - option to change http method
- [ ] - Resource page for predefined resources

### Phase 2:

- [ ] db integration
- [ ] helm integration
- [ ] helm visualization
- [ ] define resource and add in resources page
- [ ] select on the basis of selector(get all resources of app)
- [ ] save all resources
- [ ] easy switch between versions
- [ ] help
- [ ] about
- [ ] paperwork

### Phase 3:
- [ ] deletion policy for db
- [ ] integrated s3
